var module = angular.module('dataServices', []);

module.service('data', function() {
	var service = {
	};
	service.columns = [
		{'key': 'g1', 'description': 'Herbs/Spices, etc.', 'quality': 'good'},
		{'key': 'g2', 'description': 'Vegetables', 'quality': 'good'},
		{'key': 'g3', 'description': 'Legumes', 'quality': 'good'},
		{'key': 'g4', 'description': 'Fruits', 'quality': 'good'},
		{'key': 'g5', 'description': 'Nuts/Seeds', 'quality': 'good'},
		{'key': 'g6', 'description': 'LF & Sugar Dairy, etc.', 'quality': 'good'},
		{'key': 'g7', 'description': 'Lean Meats, etc.', 'quality': 'good'},
		{'key': 's1', 'description': 'Whole Grain, etc.', 'quality': 'soso'},
		{'key': 'p1', 'description': 'Bread', 'quality': 'poor'},
		{'key': 'p2', 'description': 'Beverages, etc.', 'quality': 'poor'},
		{'key': 'p3', 'description': 'Condiments', 'quality': 'poor'},
		{'key': 'p4', 'description': 'Fried/Fat Foods', 'quality': 'poor'},
		{'key': 'p5', 'description': 'Desserts', 'quality': 'poor'}
	];
	service.kinds = [
		{'key': 'herbs', 'description': 'Herbs/Spices', 'column': 'g1'},
		{'key': 'calfreebev', 'description': 'Cal-Free Bev', 'column': 'g1'},
		{'key': 'fatfreecond', 'description': 'Fat Free Cond.', 'column': 'g1'},
		{'key': 'vegetables', 'description': 'Vegetables', 'column': 'g2'},
		{'key': 'legumes', 'description': 'Legumes', 'column': 'g3'},
		{'key': 'fruits', 'description': 'Fruits', 'column': 'g4'},
		{'key': 'nuts', 'description': 'Nuts/Seeds', 'column': 'g5'},
		{'key': 'dairy', 'description': 'LF & Sugar Dairy', 'column': 'g6'},
		{'key': 'lfcondiments', 'description': 'LF Condiments', 'column': 'g6'},
		{'key': 'meats', 'description': 'Lean Meats', 'column': 'g7'},
		{'key': 'proteinbars', 'description': 'Protein Bars', 'column': 'g7'},
		{'key': 'proteindrinks', 'description': 'Protein Drinks', 'column': 'g7'},
		{'key': 'grain', 'description': 'Whole Grain', 'column': 's1'},
		{'key': 'driedfruit', 'description': 'Dried Fruit', 'column': 's1'},
		{'key': 'energybars', 'description': 'Energy Bars', 'column': 's1'},
		{'key': 'highfiber', 'description': 'High Fiber', 'column': 's1'},
		{'key': 'bread', 'description': 'Bread', 'column': 'p1'},
		{'key': 'beverages', 'description': 'Beverages', 'column': 'p2'},
		{'key': 'hsffdesserts', 'description': 'HS/FF Desserts', 'column': 'p2'},
		{'key': 'eggs', 'description': 'Eggs', 'column': 'p2'},
		{'key': 'hsffcondiments', 'description': 'HS/FF Condiments', 'column': 'p2'},
		{'key': 'fatcondiments', 'description': 'Condiments', 'column': 'p3'},
		{'key': 'fried', 'description': 'Fried/Fat Foods', 'column': 'p4'},
		{'key': 'fatdesserts', 'description': 'Desserts', 'column': 'p5'}
	];
	service.items = [
		{'key': 'basil', 'description': 'Basil', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'cinnamon', 'description': 'Cinnamon', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'cilantro', 'description': 'Cilantro', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'cumin', 'description': 'Cumin', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'dill', 'description': 'Dill', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'ginger', 'description': 'Ginger', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'oregano', 'description': 'Oregano', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'parsley', 'description': 'Parsley', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'rosemary', 'description': 'Rosemary', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'sage', 'description': 'Sage', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'thyme', 'description': 'Thyme', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'tumeric', 'description': 'Tumeric', 'kind': 'herbs', 'quality': 'good', 'points': 0},
		{'key': 'coffee', 'description': 'Coffee', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'crystallight', 'description': 'Crystal Light', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'dietsodas', 'description': 'Diet Sodas', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'propel', 'description': 'Propel', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'sugfreejello', 'description': 'Sug-Free Jello', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'unsweettea', 'description': 'Unsweet Tea', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'water', 'description': 'Water', 'kind': 'calfreebev', 'quality': 'good', 'points': 0},
		{'key': 'mustard', 'description': 'Mustard', 'kind': 'fatfreecond', 'quality': 'good', 'points': 0},
		{'key': 'vinegar', 'description': 'Vinegar', 'kind': 'fatfreecond', 'quality': 'good', 'points': 0},
		{'key': 'worcestershire', 'description': 'Worcestershire', 'kind': 'fatfreecond', 'quality': 'good', 'points': 0},
		{'key': 'asparagus', 'description': 'Asparagus (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'beets', 'description': 'Beets (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'broccoli', 'description': 'Broccoli (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'brusselssprouts', 'description': 'Brussels sprouts (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'cabbage', 'description': 'Cabbage (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'carrots', 'description': 'Carrots (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'cauliflower', 'description': 'Cauliflower (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'celery', 'description': 'Celery (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'collardgreens', 'description': 'Collard greens (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'cucumber', 'description': 'Cucumber (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'eggplant', 'description': 'Eggplant (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'greenbeans', 'description': 'Green Beans (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'kale', 'description': 'Kale (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'lettuce', 'description': 'Lettuce (4c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'mixedgreens', 'description': 'Mixed Greens (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'mushrooms', 'description': 'Mushrooms (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'okra', 'description': 'Okra (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'onion', 'description': 'Onion (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'peas', 'description': 'Peas (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'pepper', 'description': 'Pepper (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'spinach', 'description': 'Spinach (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'sprouts', 'description': 'Sprouts (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'squash', 'description': 'Squash (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'sweetpotato', 'description': 'Sweet Potato (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'zucchini', 'description': 'Zucchini (1/2c)', 'kind': 'vegetables', 'quality': 'good', 'points': 1},
		{'key': 'adzukibeans', 'description': 'Adzuki beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'blackbeans', 'description': 'Black beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'blackeyepeas', 'description': 'Black-eye-peas (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'garbonzobeans', 'description': 'Garbonzo beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'kidneybeans', 'description': 'Kidney beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'lentils', 'description': 'Lentils  (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'limabeans', 'description': 'Lima beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'navybeans', 'description': 'Navy beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'northernbeans', 'description': 'Northern beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'pintobeans', 'description': 'Pinto beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'redbeans', 'description': 'Red beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'soybeans', 'description': 'Soy beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'whitebeans', 'description': 'White beans (1/2c)', 'kind': 'legumes', 'quality': 'good', 'points': 2},
		{'key': 'apple', 'description': 'Apple (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'apricots', 'description': 'Apricots (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'banana', 'description': 'Banana (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'blackberries', 'description': 'Blackberries (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'blueberries', 'description': 'Blueberries (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'cantaloupe', 'description': 'Cantaloupe (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'cherries', 'description': 'Cherries (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'cranberries', 'description': 'Cranberries (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'grapefruit', 'description': 'Grapefruit (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'grapes', 'description': 'Grapes (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'honeydew', 'description': 'Honeydew (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'kiwi', 'description': 'Kiwi (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'mango', 'description': 'Mango (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'nectarine', 'description': 'Nectarine (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'orange', 'description': 'Orange (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'peach', 'description': 'Peach (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'pear', 'description': 'Pear (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'pineapple', 'description': 'Pineapple (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'pomegranate', 'description': 'Pomegranate (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'plum', 'description': 'Plum (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'raspberries', 'description': 'Raspberries (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'strawberries', 'description': 'Strawberries (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'tangerine', 'description': 'Tangerine (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'tomato', 'description': 'Tomato (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'watermelon', 'description': 'Watermelon (1/2c)', 'kind': 'fruits', 'quality': 'good', 'points': 3},
		{'key': 'almonds', 'description': 'Almonds (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'avocado', 'description': 'Avocado (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'brazilnuts', 'description': 'Brazilnuts (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'cashews', 'description': 'Cashews (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'olives', 'description': 'Olives (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'peanuts', 'description': 'Peanuts (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'pecans', 'description': 'Pecans (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'pistachios', 'description': 'Pistachios (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'nutbutter', 'description': 'Nut butter (1Tbsp)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'seeds', 'description': 'Seeds (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'walnuts  ', 'description': 'Walnuts   (1/4c)', 'kind': 'nuts', 'quality': 'good', 'points': 4},
		{'key': 'litealmondmilk', 'description': 'Lite Almond milk (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'lfcheese', 'description': 'LF cheese (2oz)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'ffplgkyogurt', 'description': 'FF Pl Gk Yogurt (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'lfcottagech', 'description': 'LF Cottage Ch  (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'lfkefiir', 'description': 'LF Kefir (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'lfyogurt', 'description': 'LF Yogurt  (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'lightsoy', 'description': 'Light Soy (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'skimmilk', 'description': 'Skim Milk (1c)', 'kind': 'dairy', 'quality': 'good', 'points': 5},
		{'key': 'bbqsauce', 'description': 'BBQ sauce (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'cacao', 'description': 'Cacao - Ground (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'chickenbroth', 'description': 'Chicken broth (1/2c)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'ffdressing', 'description': 'FF Dressing (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'ffmayonnaise', 'description': 'FF Mayonnaise (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'halfhalf', 'description': 'Half & half (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'hummus', 'description': 'Hummus (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'ketchup', 'description': 'Ketchup (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'preserves', 'description': 'Preserves (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'salsa', 'description': 'Salsa (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'spaghettisauce', 'description': 'Spaghetti sauce (1Tbsp)', 'kind': 'lfcondiments', 'quality': 'good', 'points': 3},
		{'key': 'beef97lean', 'description': 'Beef (97% lean) (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'chickenbreast', 'description': 'Chicken breast (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'eggwhites', 'description': 'Egg Whites (8)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'fish', 'description': 'Fish (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'hamlean', 'description': 'Ham (lean) (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'porkloin', 'description': 'Pork loin (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'smartdog', 'description': 'Smart Dog (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'turkey', 'description': 'Turkey (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'eggbeaters', 'description': 'Egg beaters (1c)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'bocaburger', 'description': 'Boca burger (3oz)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'tofu', 'description': 'Tofu (3/4c)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'shrimp', 'description': 'shrimp (12)', 'kind': 'meats', 'quality': 'good', 'points': 6},
		{'key': 'questbar', 'description': 'Quest Bar (1bar)', 'kind': 'proteinbars', 'quality': 'good', 'points': 6},
		{'key': 'pureprotein', 'description': 'Pure Protein (1bar)', 'kind': 'proteinbars', 'quality': 'good', 'points': 6},
		{'key': 'myoplex', 'description': 'Myoplex (8oz)', 'kind': 'proteindrinks', 'quality': 'good', 'points': 6},
		{'key': 'musclemilk', 'description': 'Muscle milk (8oz)', 'kind': 'proteindrinks', 'quality': 'good', 'points': 6},
		{'key': 'brownrice', 'description': 'Brown rice (1c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'corn', 'description': 'Corn (1/2c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'ffpopcorn', 'description': 'FF popcorn (4c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'oatmeal', 'description': 'Oatmeal (1c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'quiona', 'description': 'Quinoa (1c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'wwbread', 'description': 'ww bread (2sl)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'wwcereal', 'description': 'ww cereal (1/2c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'wwpasta', 'description': 'ww pasta (1c)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'wwwrap', 'description': 'ww wrap (1)', 'kind': 'grain', 'quality': 'soso', 'points': 7},
		{'key': 'dates', 'description': 'Dates (1/4c)', 'kind': 'driedfruit', 'quality': 'soso', 'points': 7},
		{'key': 'cranberries', 'description': 'Cranberries (1/4c)', 'kind': 'driedfruit', 'quality': 'soso', 'points': 7},
		{'key': 'raisins', 'description': 'Raisins (1/4c)', 'kind': 'driedfruit', 'quality': 'soso', 'points': 7},
		{'key': 'cliff', 'description': 'Cliff (1)', 'kind': 'energybars', 'quality': 'soso', 'points': 7},
		{'key': 'powerbar', 'description': 'Powerbar (1)', 'kind': 'energybars', 'quality': 'soso', 'points': 7},
		{'key': 'branbuds', 'description': 'Bran Buds (1/2c)', 'kind': 'highfiber', 'quality': 'soso', 'points': 3},
		{'key': 'fiberoneorig', 'description': 'Fiber One (orig) (1/2c)', 'kind': 'highfiber', 'quality': 'soso', 'points': 3},
		{'key': 'goleanorig', 'description': 'Go Lean (orig) (1/2c)', 'kind': 'highfiber', 'quality': 'soso', 'points': 3},
		{'key': 'olehighfiberwrap', 'description': 'Ole High Fiber Wrap (2)', 'kind': 'highfiber', 'quality': 'soso', 'points': 3},
		{'key': 'bagel', 'description': 'Bagel  (1)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'bakedchips', 'description': 'Baked Chips(1c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'bun', 'description': 'Bun (1)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'cereal', 'description': 'Cereal (1c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'crackers', 'description': 'Crackers (6)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'granolabar', 'description': 'Granola Bar (2)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'grits', 'description': 'Grits  (1c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'loafbread', 'description': 'Loaf Bread (2sl)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'pancakes', 'description': 'Pancakes (1)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'pasta', 'description': 'Pasta (1c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'potatoes', 'description': 'Potatoes (1c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'pretzels', 'description': 'Pretzels (1/2c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'rice', 'description': 'Rice (1c)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'ricecakes', 'description': 'Rice cakes 3', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'waffle', 'description': 'Waffle (1)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'wrap', 'description': 'Wrap (1)', 'kind': 'bread', 'quality': 'poor', 'points': 8},
		{'key': 'alcohol', 'description': 'Alcohol (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'fruitjuice', 'description': 'Fruit Juice (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'koolaid', 'description': 'Kool-aid (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'sodasugar', 'description': 'Soda - sugar (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'sweettea', 'description': 'Sweet tea (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'gatorade', 'description': 'Gatorade (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'powerade', 'description': 'Powerade (8oz)', 'kind': 'beverages', 'quality': 'poor', 'points': 9},
		{'key': 'cookiesff', 'description': 'Cookies FF (2)', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'ffcoolwhip', 'description': 'FF Cool Whip (1/4c) ', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'ffpudding', 'description': 'FF Pudding (1/2c) ', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'jello', 'description': 'Jello (1/2c)', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'lffrozonyogurt', 'description': 'LF Frozen Yogurt (1c)', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'poptarts', 'description': 'Pop Tarts (2)', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'sorbet', 'description': 'Sorbet (1/2c)', 'kind': 'hsffdesserts', 'quality': 'poor', 'points': 9},
		{'key': 'eggs', 'description': 'Eggs with Yolk (2)', 'kind': 'eggs', 'quality': 'poor', 'points': 9},
		{'key': 'honey', 'description': 'Honey (1Tbsp)', 'kind': 'hsffcondiments', 'quality': 'poor', 'points': 5},
		{'key': 'jelly ', 'description': 'Jelly  (1Tbsp)', 'kind': 'hsffcondiments', 'quality': 'poor', 'points': 5},
		{'key': 'sugar ', 'description': 'Sugar  (1Tbsp)', 'kind': 'hsffcondiments', 'quality': 'poor', 'points': 5},
		{'key': 'syrup', 'description': 'Syrup (1Tbsp)', 'kind': 'hsffcondiments', 'quality': 'poor', 'points': 5},
		{'key': 'butter', 'description': 'Butter (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'creamcheese', 'description': 'Cream Cheese (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'dressing', 'description': 'Dressing (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'margarine', 'description': 'Margarine (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'mayonnaise', 'description': 'Mayonnaise (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'oil', 'description': 'Oil (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'sourcream', 'description': 'Sour Cream (1Tbsp)', 'kind': 'fatcondiments', 'quality': 'poor', 'points': 10},
		{'key': 'bacon', 'description': 'Bacon (2strips)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'cheese', 'description': 'Cheese (2oz)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'chicken', 'description': 'Chicken (2oz)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'chickennuggets', 'description': 'Chicken Nuggets (4)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'chips', 'description': 'Chips (1c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'frenchtoast', 'description': 'French Toast (2)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'fries', 'description': 'Fries (1/2c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'hamburger', 'description': 'Hamburger (1)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'hashbrown', 'description': 'Hashbrown (1/2c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'hotdog', 'description': 'Hot Dog (1)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'lasangna', 'description': 'Lasagna (1c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'onionrings', 'description': 'Onion Rings (1c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'pizza', 'description': 'Pizza (1slice)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'pulledpork', 'description': 'Pulled pork (1/2c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'ribs', 'description': 'Ribs (2)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'sausage', 'description': 'Sausage (1)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'wholemilk', 'description': 'Whole Milk (1c)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'wings', 'description': 'Wings (2)', 'kind': 'fried', 'quality': 'poor', 'points': 11},
		{'key': 'brownies', 'description': 'Brownies (1)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'cake', 'description': 'Cake (1slice)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'candybar', 'description': 'Candy Bar (1)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'chocolate', 'description': 'Chocolate (1oz)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'cookies', 'description': 'Cookies (2)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'crumble', 'description': 'Crumble (1)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'doughnut', 'description': 'Doughnut (1)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'icecream', 'description': 'Ice Cream (1c)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'muffin', 'description': 'Muffin (1)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12},
		{'key': 'pie', 'description': 'Pie (1slice)', 'kind': 'fatdesserts', 'quality': 'poor', 'points': 12}
        ];
	service.totals = [ 
		{key: 'points', name: 'Points'},
		{key: 'vegetables', name: 'Vegetables'},
		{key: 'legumes', name: 'Legumes'},
		{key: 'fruits', name: 'Fruits'},
		{key: 'nuts', name: 'Nuts/Seeds'},
		{key: 'dairy', name: 'LF & Sugar Dairy'},
		{key: 'meats', name: 'Lean Meats'},
		{key: 'grain', name: 'Whole Grain'}
	];
	service.plans = {
		success: {
			points: {min: 42, max: 57},
			vegetables: {min: 4},
			legumes: {min: 1, max: 2},
			fruits: {min: 1, max: 2},
			nuts: {min: 1, max: 2},
			dairy: {min: 2, max: 3},
			meats: {min: 2, max: 2},    				
			grain: {min: 1, max: 1}
		},
		champion: {
			points: {min: 46, max: 61},
			vegetables: {min: 5},
			legumes: {min: 1, max: 2},
			fruits: {min: 2, max: 3},
			nuts: {min: 1, max: 2},
			dairy: {min: 2, max: 3},
			meats: {min: 2, max: 2},    				
			grain: {min: 1, max: 1}
		}, 
		achieve: {
			points: {min: 66, max: 74},
			vegetables: {min: 6},
			legumes: {min: 3, max: 3},
			fruits: {min: 3, max: 3},
			nuts: {min: 2, max: 3},
			dairy: {min: 2, max: 3},
			meats: {min: 2, max: 3},    				
			grain: {min: 1, max: 1}
		}
	};
	service.inRange = function(value, min, max) {
		var inRg = false;
		if (max) {
			if (value >= min && value <= max) {
				inRg= true;
			}
		} else {
			if (value >= min) {
				inRg = true;
			}
		}
		return inRg;
	};
	return service;
});
